export const maps = [
  "Jungle",
  "Desert",
  "Swamp",
  "Snowy Mountains",
  "Volcano",
  "Tower",
  "Forest & Hills",
  "Great Forest",
  "Gorge",
  "Small Arena",
  "Large Arena",
  "Town",
  "Fortress",
  "Castle Schrade",
];

export const monsters = [
  "UNK",
  "Rathian",
  "Fatalis",
  "Kelbi",
  "Mosswine",
  "Bullfango",
  "Yian Kut-Ku",
  "Lao-Shan Lung",
  "Cephadrome",
  "Felyne",
  "Veggie Elder",
  "Rathalos",
  "Aptonoth",
  "Genprey",
  "Diablos",
  "Khezu",
  "Velociprey",
  "Gravios",
  "Felyne?",
  "Vespoid",
  "Gypceros",
  "Plesioth",
  "Basarios",
  "Melynx",
  "Hornetaur",
  "Apceros",
  "Monoblos",
  "Velocidrome",
  "Gendrome",
  "Rocks",
  "Ioprey",
  "Iodrome",
  "Pugis",
  "Kirin",
  "Cephalos",
  "Giaprey / Giadrome",
  "Crimson Fatalis",
  "Pink Rathian",
  "Blue Yian Kut-Ku",
  "Purple Gypceros",
  "Yian Garuga",
  "Silver Rathalos",
  "Gold Rathian",
  "Black Diablos",
  "White Monoblos",
  "Red Khezu",
  "Green Plesioth",
  "Black Gravios",
  "Daimyo Hermitaur",
  "Azure Rathalos",
  "Ashen Lao-Shan Lung",
  "Blangonga",
  "Congalala",
  "Rajang",
  "Kushala Daora",
  "Shen Gaoren",
  "Great Thunderbug",
  "Shakalaka",
  "Yama Tsukami",
  "Chameleos",
  "Rusted Kushala Daora",
  "Blango",
  "Conga",
  "Remobra",
  "Lunastra",
  "Teostra",
  "Hermitaur",
  "Shogun Ceanataur",
  "Bulldrome",
  "Anteka",
  "Popo",
  "White Fatalis",
  "Yama Tsukami",
  "Ceanataur",
  "Hypnocatrice",
  "Lavasioth",
  "Tigrex",
  "Akantor",
  "Bright Hypnoc",
  "Lavasioth Subspecies",
  "Espinas",
  "Orange Espinas",
  "White Hypnoc",
  "Akura Vashimu",
  "Akura Jebia",
  "Berukyurosu",
  "Cactus",
  "Gorge Objects",
  "Gorge Rocks",
  "Pariapuria",
  "White Espinas",
  "Kamu Orugaron",
  "Nono Orugaron",
  "Raviente",
  "Dyuragaua",
  "Doragyurosu",
  "Gurenzeburu",
  "Burukku",
  "Erupe",
  "Rukodiora",
  "Unknown",
  "Gogomoa",
  "Kokomoa",
  "Taikun Zamuza",
  "Abiorugu",
  "Kuarusepusu",
  "Odibatorasu",
  "Disufiroa",
  "Rebidiora",
  "Anorupatisu",
  "Hyujikiki",
  "Midogaron",
  "Giaorugu",
  "Mi Ru",
  "Farunokku",
  "Pokaradon",
  "Shantien",
  "Pokara",
  "Dummy",
  "Goruganosu",
  "Aruganosu",
  "Baruragaru",
  "Zerureusu",
  "Gougarf",
  "Uruki",
  "Forokururu",
  "Meraginasu",
  "Diorekkusu",
  "Garuba Daora",
  "Inagami",
  "Varusaburosu",
  "Poborubarumu",
  "Duremudira",
  "UNK",
  "Felyne",
  "Blue NPC",
  "UNK",
  "Cactus",
  "Veggie Elders",
  "Gureadomosu",
  "Harudomerugu",
  "Toridcless",
  "Gasurabazura",
  "Kusubami",
  "Yama Kurai",
  "Dure 3rd Phase",
  "Zinogre",
  "Deviljho",
  "Brachydios",
  "Berserk Laviente",
  "Toa Tesukatora",
  "Barioth",
  "Uragaan",
  "Stygian Zinogre",
  "Guanzorumu",
  "Deviljho",
  "UNK",
  "Egyurasu",
  "Voljang",
  "Nargacuga",
  "Keoaruboru",
  "Zenaserisu",
  "Gore Magala",
  "Blinking Nargacuga",
  "Shagaru Magala",
  "Amatsu",
  "Eruzerion",
  "Musou Dure",
  "Rocks",
  "Seregios",
  "Bogabadorumu",
  "Unknown Blue Barrel",
  "Musou Bogabadorumu",
  "Costumed Uruki",
  "Musou Zerureusu",
  "PSO2 Rappy",
  "King Shakalaka",
];
