[package]
name = "better_cursor_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
better_cursor_core = { path= "../core" }
quote = "1.0.35"
syn = "2.0.58"
proc-macro2 = "1.0"

[lib]
proc-macro = true
path = "./lib.rs"