name: Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "apps/**"
      - "packages/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lint
      - run: yarn check-types
