name: Tests

on:
  push:
    branches:
      - main
      - development
    paths:
      - "src/**"
      - "src-tauri/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "src/**"
      - "src-tauri/**"

jobs:
  build-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lint
      - run: yarn check-types
  build-rs:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Create empty dist
        run: mkdir dist
      - name: Build
        working-directory: src-tauri
        run: cargo build --verbose
        
      - name: Test
        working-directory: src-tauri
        run: cargo test -- --test-threads=1
      
      - name: Format
        working-directory: src-tauri
        run: cargo  fmt --all -- --check