name: Rust

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "apps/editor/**"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - "apps/editor/**"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: apps/editor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        working-directory: apps/editor
        run: cargo build --verbose

      - name: Test
        working-directory: apps/editor
        run: cargo test

      - name: Format
        working-directory: apps/editor
        run: cargo  fmt --all -- --check
